### ISSUE TITLE
[Fix] 수정 중 'x' 버튼을 눌렀을 때

### ISSUE THREAD

**Issue by brixxt27** [blind-42/42byte#482]
![image](https://user-images.githubusercontent.com/83959536/158352096-df85e564-4bf0-4650-b462-34a6ddbb0c45.png)

수정을 누르고, 실수로 닫기를 누르거나 했을 때 경고 메시지는 나오지만 그 작업을 취소할 수 있는 부분은 없어 아쉽습니다.

**Comment by tamagoyakii** [comment]
빠르게 수정하겠습니다~~~!
